name: 'My frist Github Action'

on: push

env:
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
    name: 'First Job'
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Set outpue value 1
        id: first
        shell: bash
        run: |
          value1='This is the First value'

          echo "::set-output name=first_value::$value1"

      - name: Set outpue value 2
        id: second
        shell: pwsh
        run: |
          $value2 = 'This is the Second value'

          echo "::set-output name=second_value::$value2"

      - name: Check output value
        shell: bash
        run: |
          echo "first value ${{ steps.first.outputs.first_value }}"

      - name: Check output value
        shell: bash
        run: |
          echo "second value ${{ steps.second.outputs.second_value }}"