name: 'My frist Github Action'

on: push

jobs:
  first_job:
    name: 'First Job'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Say Hello world 1'
        shell: bash
        run : |
          echo "helloworld from step #1"
      - name: "Say Lorem Ipsum 1"
        shell: push
        run : |
         echo "Lorem Ipsum from step #2"