name: 'My frist Github Action'

on: push

env:
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
    name: 'First Job'
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Set environment variable 1
        shell: bash
        run: |
          echo "VAR1='This is the value from the step 1'" >> $GITHUB_ENV

    steps:
      - name: Set environment variable 2
        shell: pwsh
        run: |
          echo "VAR2='This is the value from the step 2'" |`
          Out-Fiile -FilePath $env:GITHUB_ENV -Encoding UTF-8 -Append

      - name: Check environment vvariables
        shell: bash
        run: |
          echo "preset value: ${{ env.PRESET_VALUE }}"
          echo "VAR1: $VAR1"
          echo "VAR2: $VAR2"